package kr.kkoreng.kklugin.core

import org.gradle.api.DefaultTask
import org.gradle.api.file.RegularFileProperty
import org.gradle.api.tasks.OutputFile
import org.gradle.api.tasks.TaskAction

abstract class GenerateMetadataTask: DefaultTask() {

    /**
     * Path of the file generated by this task.
     */
    @get:OutputFile
    abstract val outputFile: RegularFileProperty

    @TaskAction
    abstract fun generate()

}